import { Geist, Geist_Mono, Lexend } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import MyContainer from "@/components/MyContainer";


const lexend = Lexend({
  weight: ["100", "200", "300", "400", "500", "600", "800"],
});

// Using Local Bangla Fonts
export const fontBangla = localFont({
  src: './../fonts/mayaboti-normal.ttf',
  //  weight: 
})

export const metadata = {
  title: {
    default: "Grand Mart",
    template: "%s | Grand Mart"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <header>
          <MyContainer>
            <Navbar></Navbar>
          </MyContainer>
        </header>

        <main className="min-h-[calc(100vh-324px)]">
          <MyContainer>{children}</MyContainer>
        </main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
