import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  weight:["100","200","300","400","500","600","800"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
